Repository spacetelescope/stsci.skypac, pull requests merged in 2019-01, with the labels that each got.

#40 Fix WCS._naxis deprecation warnings; Remove Python 2 support
  setup.cfg
  setup.py
  stsci/skypac/__init__.py
  stsci/skypac/hstinfo.py
  stsci/skypac/pamutils.py
  stsci/skypac/parseat.py
  stsci/skypac/region.py
  stsci/skypac/skyline.py
  stsci/skypac/skymatch.py
  stsci/skypac/skystatistics.py
  stsci/skypac/utils.py
Labels: enhancement

#41 Update setup; dir structure; sphinx warnings
  .readthedocs.yml
  Jenkinsfile
  doc/source/LICENSE.rst
  doc/source/parseat.rst
  docs/.rtd-environment.yml
  docs/Makefile
  docs/_static/css/custom.css
  docs/_static/stsci_pri_combo_mark_white.png
  docs/make.bat
  docs/source/LICENSE.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/pamutils.rst
  docs/source/parseat.rst
  docs/source/region.rst
  docs/source/skyline.rst
  docs/source/skymatch.rst
  docs/source/skystatistics.rst
  docs/source/utils.rst
  stsci/skypac/pamutils.py
  stsci/skypac/utils.py
Labels: Documentation, enhancement

#42 Allow local install of HTML help files. Release 1.0.0
  LICENSE.txt
  MANIFEST.in
  setup.cfg
  setup.py
Labels: Documentation, enhancement

#43 Fix typo: shpinx -> sphinx
  setup.py
Labels: bug
